apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: capture-order
  labels:
    app: capture-order
spec:
  replicas: 8
  selector:
    matchLabels:
      app: capture-order
  template:
    metadata:
      labels:
        app: capture-order
    spec:
      containers:
      - name: captureorderack
        image: shanepeckham/captureorderack:v6
        ports:
        - containerPort: 8080
        env:
        - name: TEAMNAME
          value: "TEAM10"
        - name: MONGOHOST
          value: "mongodb://{{ template "mongodb.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: rabbitmq-password
              name: {{ template "rabbitmq.fullname" . }}
        - name: RABBITMQHOST
          value: "amqp://user:$(RABBITMQ_PASSWORD)@{{ template "rabbitmq.fullname" . }}.{{ .Values.namespace}}.svc.cluster.local:5672"
