apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: capture-order
  labels:
    app: capture-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capture-order
  template:
    metadata:
      labels:
        app: capture-order
    spec:
      containers:
      - name: captureorderack
        image: shanepeckham/captureorderack:v6
        ports:
        - containerPort: 8080
        env:
        - name: TEAMNAME
          value: "TEAM10"
        - name: DB_USER 
          valueFrom:
            secretKeyRef:
              name: middleware-secrets
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: middleware-secrets
              key: DB_PASS
        - name: AMQP_USER 
          valueFrom:
            secretKeyRef:
              name: middleware-secrets
              key: AMQP_USER
        - name: AMQP_PASS
          valueFrom:
            secretKeyRef:
              name: middleware-secrets
              key: AMQP_PASS
        - name: MONGOHOST
          value: "mongodb://$(DB_USER):$(DB_PASS)@mongodb-mongodb.ci.svc.cluster.local/db"
        - name: RABBITMQHOST 
          value: "amqp://$(AMQP_USER):$(AMQP_PASS)@rabbit-rabbitmq.ci.svc.cluster.local:5672/"
